# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Josh Lindsey"
timezone:           "America/New_York"
encoding:           "utf-8"

# URL
baseurl:            ""
permalink:          /posts/:title.html

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "Github"
    href:           "https://github.com/jlindsey"
  - name:           "Twitter"
    href:           "https://twitter.com/lesmothian"

# Sass
sass:
  style:            :compressed

gems:
  - jekyll-gist

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
